-- vim.cmd("colorscheme citruszest")
vim.cmd("colorscheme moonfly")

-- require('rose-pine').setup({
--   variant = 'auto',
--   dark_variant = 'main',
--   bold_vert_split = false,
--   dim_nc_background = false,
--   disable_background = false,
--   disable_float_background = false,
--   disable_italics = false,
--   groups = {
--               background = '#080808',
--   }
-- })
-- vim.cmd.colorscheme 'rose-pine'
--  local palettes = {
--    carbonfox = {
--     bg1 = "#080808",
--     -- bg1 = "#121212",
--    },
--  }
--  local specs = {
--    carbonfox = {
--      syntax = {
--        string = "#66ffbf"
--      }
--    }
--  }
--
--  require('nightfox').setup({
--    palettes = palettes,
--    specs = specs,
-- })
-- vim.cmd.colorscheme 'carbonfox'
